### ISSUE TITLE
doesn't work on 1.20.6

### ISSUE THREAD

**Issue by nickademas** [Enchanted-Games/vertical-slabs#34]
![obraz](https://github.com/Enchanted-Games/vertical-slabs/assets/46594867/3ade4f7d-8d39-4d11-9a0e-4621435541ce)
ummmm

**Comment by pnk2u** [comment]
Unfortunately, the creator made a little syntax mistake in the fabric.mod.json file.
Instead of
`"minecraft": "1.20.5,1.20.6",`
it should say:
`"minecraft": ["1.20.5", "1.20.6"],`
Once they realize they will surely quickly fix this error but until then: 
If you have something like 7zip or winrar installed, you can open the jar of the mod, edit the file called fabric.mod.json changing the line I mentioned and then replace the file in the archive. Then you will able to run this version of the mod.

**Comment by nickademas** [comment]
i removed dependencies for it in fabric_loader_dependencies.json and it's working

**Comment by pnk2u** [comment]
I guess that also works and is easier, fair enough.

**Comment by Enchanted-Games** [comment]
actually fixed now in v1.10.4
